public enum TipoConversor {
    CELSIUS_PARA_FAHRENHEIT,
    FAHRENHEIT_PARA_CELSIUS,
    CELSIUS_PARA_KELVIN,
    KELVIN_PARA_CELSIUS,
    FAHRENHEIT_PARA_KELVIN,
    KELVIN_PARA_FAHRENHEIT,
    IDENTIDADE,
    METROS_PARA_QUILOMETROS,
    QUILOMETROS_PARA_METROS,
    MILHAS_PARA_QUILOMETROS,
    QUILOMETROS_PARA_MILHAS,
}
